app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, Length


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6)])
    submit = SubmitField('Register')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import sys
print(sys.executable)
app = Flask(__name__)
app.config.from_object(Config)
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
migrate = Migrate(app, db)

from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)
from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)

from app.blueprints.auth import models

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.blueprints.main import routes

app/blueprints/main/routes.py
from . import bp
from flask import render_template

@bp.route('/')
def home():
    matrix = {
        'instructors': ('Dr. Chuck', 'Charles Severance'),
        'students': ['Rex', 'Ryan', 'Randy', 'Ralph']
    }
    return render_template('index.jinja', title = 'Home', instructors = matrix['instructors'], students = matrix['students'])

@bp.route('/about')
def about():
    return render_template('about.jinja', title = 'About')

app/templates/about.jinja
{% extends "base.jinja" %}
{% block content %}
    <h1>About Page</h1>
{% endblock %}

app/templates/base.jinja
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='index.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>Matrix Facebook</title>
    {% endif %}
</head>
<body>
    {% include "navbar.jinja" %}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
    {% for message in messages %}
    <li>{{message}}</li>
    {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <h1>Matrix Facebook</h1>
    {% block content %}
    
    {% endblock  %}
</body>
</html>

app/templates/index.jinja
{% extends "base.jinja" %}
{% block content %}

<h3>Instructors</h3>
<p>{{instructors[0]}} {{instructors[1]}}</p>
<h3>Students</h3>
{% for i in students %}
<p>{{i.title()}}</p>
{% endfor %}

{% endblock %}

app/templates/navbar.jinja
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">MATRIX FACEBOOK</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for ('main.home')}}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.about')}}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/auth/register">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for ('auth.signin')}}">Signin</a>
          </li>
          <li class="nav-item dropdown">
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/templates/register.jinja
{% extends "base.jinja" %}
{% block content %}
    <h1>Register</h1>
    <form action="" method="post">
    <p>
        {{form.username.label}} <br>
        {{form.username(size = 32) }}
    </p>
    <p>
        {{form.email.label}} <br>
        {{form.email(size = 32) }}
        {% for error in form.email.errors %}
            <span style="color: red;">{{error}}</span>
        {% endfor %}
        
        
    </p>
    <p>
        {{form.password.label}} <br>
        {{form.password(size = 32) }}
        {% for error in form.password.errors %}
            <span style="color: red;">{{error}}</span>
        {% endfor %}
    </p>
    <p>
        {{form.submit() }}
    </p>
    </form>
{% endblock %}

app/templates/signin.jinja
{% extends "base.jinja" %}
{% block content %}
    <h1>Sign in</h1>
{% endblock %}